name: Security Scanning Image
on: [push]
jobs:
  Build_and_Scan_Image:
    runs-on: self-hosted # Or [self-hosted, label-1] 
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Check version Trivy
        run: |
          pwd 
          trivy --version
          echo ${{ github.workspace }}
          echo ${{ github.action}}
          echo ${{ github.job }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Scan Dockerfile
        run: trivy config --exit-code 1 --severity CRITICAL,HIGH,MEDIUM .
      # - name: Build Image
      #   run: docker build -t dashboard .
      - name: Scan Image
        run: trivy image --exit-code 1 --severity CRITICAL,HIGH ghcr.io/kiennkt/kiennkt/tender_document_generator:v1.28
        # run: trivy image --exit-code 1 --severity CRITICAL,HIGH kienkt/dashboard-react-app:latest
      
      - name: Inspect image
        run: docker inspect ghcr.io/kiennkt/kiennkt/tender_document_generator:v1.28
      #- name: Build Image
        #run: docker run --name dashboard-app -dp 9999:80 kienkt/dashboard-react-app:latest
