name: Security Scanning Image
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Build_and_Scan_Image:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Check version Trivy
        run: |
          pwd 
          trivy --version
      - name: Scan Dockerfile
        run: trivy config --exit-code 1 --severity CRITICAL,HIGH,MEDIUM .

      # - name: Build Image
      #   run: docker build -t dashboard .
      - name: Login Docker hub
        run: 
      - name: Scan Image
        run: trivy image --exit-code 1 --severity CRITICAL,HIGH kienkt/dashboard-react-app:latest

      - name: Build Image
        run: docker run --name dashboard-app -dp 9999:80 kienkt/dashboard-react-app:latest

      # - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      # - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      # - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      # - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      # - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      # - name: List files in the repository
      #   run: |
      #     ls ${{ github.workspace }}
      # - run: echo "🍏 This job's status is ${{ job.status }}."

      