name: Security Scanning Image
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Build_and_Scan_Image:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Check version Trivy
        run: |
          pwd 
          trivy --version
      - name: Scan Dockerfile
        run: trivy config --exit-code 1 --severity CRITICAL,HIGH,MEDIUM .
      # - name: Build Image
      #   run: docker build -t dashboard .
      - name: Scan Image
      
        run: trivy image --exit-code 1 --severity CRITICAL,HIGH kienkt/dashboard-react-app:latest

      - name: Build Image
        run: docker run --name dashboard-app -dp 9999:80 kienkt/dashboard-react-app:latest
